name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      CMAKE_CXX_STANDARD:
        description: "CMake C++ Standard"
        default: "17"
        type: choice
        required: true
        options:
          - "11"
          - "14"
          - "17"
      ROOT_VERSION:
        description: "ROOT Version (GitHub branch / tag / commit)"
        required: true
        default: "v6-26-00"
      GEANT4_VERSION:
        description: "Geant4 Version (GitHub branch / tag / commit)"
        required: true
        default: "v11.0.1"
      GARFIELD_VERSION:
        description: "Garfield Version (GitLab branch / tag / commit)"
        required: true
        default: "4ac1e62f"

      target:
        description: Name of the runner to build the image on
        default: ubuntu-latest
        required: true
        type: choice
        options:
          - ubuntu-latest
          - self-hosted

      rest-for-physics:
        description: Use this tag as the default image for testing `rest-for-physics` framework
        type: boolean
        required: true
        default: false

env:
  IMAGE_NAME: lobis/root-geant4-garfield
  VERSION_TAG: cpp${{ github.event.inputs.CMAKE_CXX_STANDARD }}_ROOT-${{ github.event.inputs.ROOT_VERSION }}_Geant4-${{ github.event.inputs.GEANT4_VERSION }}_Garfield-${{ github.event.inputs.GARFIELD_VERSION }}

jobs:
  build-and-push-image:
    runs-on: ${{ github.event.inputs.target }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}

      - name: Build parent to base image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          pull: false
          build-args: |
            CMAKE_CXX_STANDARD=${{ github.event.inputs.CMAKE_CXX_STANDARD }}
            ROOT_VERSION=${{ github.event.inputs.ROOT_VERSION }}
            GEANT4_VERSION=${{ github.event.inputs.GEANT4_VERSION }}
            GARFIELD_VERSION=${{ github.event.inputs.GARFIELD_VERSION }}
          tags: |
            action/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Generate final base Dockerfile with Geant4 dataset environment variables
        run: |
          python3 utils/geant4-dataset-dockerfile.py --image action/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }} --output utils/Dockerfile
          cat utils/Dockerfile

      - name: Build and Push base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: utils/Dockerfile
          push: true
          pull: false
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Add additional tag to base image and push it
        if: ${{ github.event.inputs.rest-for-physics == 'true' }}
        run: |
          docker tag ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }} ghcr.io/${{ env.IMAGE_NAME }}:rest-for-physics
          docker push ghcr.io/${{ env.IMAGE_NAME }}:rest-for-physics

      - name: Build and Push development image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: development/Dockerfile
          push: true
          pull: true
          build-args: |
            CMAKE_CXX_STANDARD=${{ github.event.inputs.CMAKE_CXX_STANDARD }}
            ROOT_VERSION=${{ github.event.inputs.ROOT_VERSION }}
            GEANT4_VERSION=${{ github.event.inputs.GEANT4_VERSION }}
            GARFIELD_VERSION=${{ github.event.inputs.GARFIELD_VERSION }}
            PASSWORD=${{ secrets.DEVELOPMENT_PASSWORD }}
            SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY }}
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-dev:${{ env.VERSION_TAG }}
            ghcr.io/${{ env.IMAGE_NAME }}-dev:latest

      - name: Add additional tag to development image and push it
        if: ${{ github.event.inputs.rest-for-physics == 'true' }}
        run: |
          docker tag ghcr.io/${{ env.IMAGE_NAME }}-dev:${{ env.VERSION_TAG }} ghcr.io/${{ env.IMAGE_NAME }}-dev:rest-for-physics
          docker push ghcr.io/${{ env.IMAGE_NAME }}-dev:rest-for-physics
