name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      CMAKE_CXX_STANDARD:
        description: "CMake C++ Standard (11, 14, 17, ...)"
        required: true
        default: "17"
      ROOT_VERSION:
        description: "ROOT Version (GitHub branch / tag / commit)"
        required: true
        default: "v6-26-00"
      GEANT4_VERSION:
        description: "Geant4 Version (GitHub branch / tag / commit)"
        required: true
        default: "v11.0.1"
      GARFIELD_VERSION:
        description: "Garfield Version (GitLab branch / tag / commit)"
        required: true
        default: "af4a1451"

      target:
        required: true
        description: Name of the runner to build the image on (self-hosted, ubuntu-latest, ...)
        default: ubuntu-latest

env:
  IMAGE_NAME: lobis/root-geant4-garfield
  VERSION_TAG: cpp${{ github.event.inputs.CMAKE_CXX_STANDARD }}_ROOT-${{ github.event.inputs.ROOT_VERSION }}_Geant4-${{ github.event.inputs.GEANT4_VERSION }}_Garfield-${{ github.event.inputs.GARFIELD_VERSION }}

jobs:
  build-and-push-image:
    runs-on: ${{ github.event.inputs.target }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build parent image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          build-args: |
            CMAKE_CXX_STANDARD=${{ github.event.inputs.CMAKE_CXX_STANDARD }}
            ROOT_VERSION=${{ github.event.inputs.ROOT_VERSION }}
            GEANT4_VERSION=${{ github.event.inputs.GEANT4_VERSION }}
            GARFIELD_VERSION=${{ github.event.inputs.GARFIELD_VERSION }}
          tags: |
            action/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Generate final Dockerfile with Geant4 dataset environment variables
        run: |
          python3 utils/geant4-dataset-dockerfile.py --image action/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }} --output utils/Dockerfile
          cat utils/Dockerfile

      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: utils/Dockerfile
          push: true
          pull: false
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
            docker.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Build and Push development image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: development/Dockerfile
          push: true
          pull: true
          build-args: |
            CMAKE_CXX_STANDARD=${{ github.event.inputs.CMAKE_CXX_STANDARD }}
            ROOT_VERSION=${{ github.event.inputs.ROOT_VERSION }}
            GEANT4_VERSION=${{ github.event.inputs.GEANT4_VERSION }}
            GARFIELD_VERSION=${{ github.event.inputs.GARFIELD_VERSION }}
            PASSWORD=${{ secrets.DEVELOPMENT_PASSWORD }}
            SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY }}
          tags: |
            docker.io/${{ env.IMAGE_NAME }}-dev:${{ env.VERSION_TAG }}
            docker.io/${{ env.IMAGE_NAME }}-dev:latest
            ghcr.io/${{ env.IMAGE_NAME }}-dev:${{ env.VERSION_TAG }}
            ghcr.io/${{ env.IMAGE_NAME }}-dev:latest
